#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Vehicle diagnostic address and the four supplied pressure DIDs.
 * Mazda MX-5 ND BCM / TPMS mapping:
 *   0x2A08: Front Left
 *   0x2A06: Front Right
 *   0x2A07: Rear Left
 *   0x2A05: Rear Right */
#define BOOST_TPMS_UDS_ECU_ID 0x720u
#define BOOST_TPMS_DID_FL 0x2A08u
#define BOOST_TPMS_DID_FR 0x2A06u
#define BOOST_TPMS_DID_RL 0x2A07u
#define BOOST_TPMS_DID_RR 0x2A05u

#define BOOST_TPMS_RAW_TO_KPA 1.373f
#define BOOST_TPMS_KPA_TO_PSI 0.145037738f

typedef enum {
    BOOST_TPMS_WHEEL_FL = 0,
    BOOST_TPMS_WHEEL_FR,
    BOOST_TPMS_WHEEL_RL,
    BOOST_TPMS_WHEEL_RR,
    BOOST_TPMS_WHEEL_INVALID = -1,
} boost_tpms_protocol_wheel_t;

/* The raw value is converted to kPa first, then the replacement calibration
 * offset is added. This is deliberately additive: a replacement sensor needs a
 * new zero/reference offset, not a silently invented gain correction. */
float boost_tpms_protocol_raw_to_kpa(uint16_t raw, float replacement_offset_kpa);
float boost_tpms_protocol_kpa_to_psi(float kpa);
float boost_tpms_protocol_raw_to_psi(uint16_t raw, float replacement_offset_kpa);

boost_tpms_protocol_wheel_t boost_tpms_protocol_wheel_for_did(uint16_t did);
uint16_t boost_tpms_protocol_did_for_wheel(boost_tpms_protocol_wheel_t wheel);
bool boost_tpms_protocol_make_read_did(uint16_t did, uint8_t out_request[3]);

/* Positive UDS ReadDataByIdentifier response: 0x62, DID high, DID low, then a
 * one-byte raw value (the MX-5 ND TPMS format) or a two-byte raw value. No
 * write/control command is generated by this module. */
bool boost_tpms_protocol_parse_uds_response(const uint8_t *payload, size_t length,
                                            uint16_t *out_did, uint16_t *out_raw);


#ifdef __cplusplus
}
#endif
