#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Vehicle diagnostic address and the four supplied pressure DIDs. */
#define BOOST_TPMS_UDS_ECU_ID 0x720u
#define BOOST_TPMS_DID_FL 0x2A05u
#define BOOST_TPMS_DID_FR 0x2A07u
#define BOOST_TPMS_DID_RL 0x2A06u
#define BOOST_TPMS_DID_RR 0x2A08u

#define BOOST_TPMS_ISOTP_MAX_PAYLOAD 64u
#define BOOST_TPMS_RAW_TO_KPA 1.373f
#define BOOST_TPMS_KPA_TO_PSI 0.145037738f

typedef enum {
    BOOST_TPMS_WHEEL_FL = 0,
    BOOST_TPMS_WHEEL_FR,
    BOOST_TPMS_WHEEL_RL,
    BOOST_TPMS_WHEEL_RR,
    BOOST_TPMS_WHEEL_INVALID = -1,
} boost_tpms_protocol_wheel_t;

/* The raw value is converted to kPa first, then the replacement calibration
 * offset is added. This is deliberately additive: a replacement sensor needs a
 * new zero/reference offset, not a silently invented gain correction. */
float boost_tpms_protocol_raw_to_kpa(uint16_t raw, float replacement_offset_kpa);
float boost_tpms_protocol_kpa_to_psi(float kpa);
float boost_tpms_protocol_raw_to_psi(uint16_t raw, float replacement_offset_kpa);

boost_tpms_protocol_wheel_t boost_tpms_protocol_wheel_for_did(uint16_t did);
uint16_t boost_tpms_protocol_did_for_wheel(boost_tpms_protocol_wheel_t wheel);
bool boost_tpms_protocol_make_read_did(uint16_t did, uint8_t out_request[3]);

/* Positive UDS ReadDataByIdentifier response: 0x62, DID high, DID low, raw
 * high, raw low. No write/control command is generated by this module. */
bool boost_tpms_protocol_parse_uds_response(const uint8_t *payload, size_t length,
                                            uint16_t *out_did, uint16_t *out_raw);

typedef enum {
    BOOST_TPMS_ISOTP_INCOMPLETE = 0,
    BOOST_TPMS_ISOTP_COMPLETE,
    BOOST_TPMS_ISOTP_ERROR,
} boost_tpms_isotp_result_t;

typedef struct {
    uint8_t payload[BOOST_TPMS_ISOTP_MAX_PAYLOAD];
    size_t expected_length;
    size_t received_length;
    uint8_t next_sequence;
    bool active;
} boost_tpms_isotp_parser_t;

void boost_tpms_isotp_init(boost_tpms_isotp_parser_t *parser);
boost_tpms_isotp_result_t boost_tpms_isotp_feed(boost_tpms_isotp_parser_t *parser,
                                                 const uint8_t *frame, size_t length,
                                                 const uint8_t **out_payload,
                                                 size_t *out_length);

#ifdef __cplusplus
}
#endif
